import logging
logger = logging.getLogger(__name__)
import pandas as pd
import streamlit as st
import requests
from modules.nav import SideBarLinks

# Call the SideBarLinks from the nav module in the modules directory
SideBarLinks()

# set the header of the page
st.header('Research Opportunities')

# You can access the session state to make a more customized/personalized app experience
st.write(f"### Hi, {st.session_state['first_name']}.")

# add a button to use get all the research opportunities
if st.button('See All Opportunities',
             type='primary'):
  results = requests.get('http://api:4000/o/opportunities').json()
  
  if results.response_code == 200:
       for opportunity in results:
            position_name = opportunity.get('Name', 'No Title')
            research_area = opportunity.get('ResearchArea', 'No Research Area')
            description = opportunity.get('Description', 'No description available.')
            department_id = opportunity.get('DepartmentId', 'No Department')
            professor_id = opportunity.get('OwnerId', 'No Professor')
            created_at = opportunity.get('CreatedAt', 'No Date Available')
            
            result1 = requests.get(f'http://api:4000/d/departments/d{department_id}').json()
            department_name = result1[0].get('Name', 'No Name')
            
            result2 = requests.get(f'http://api:4000/pr/professors/p{professor_id}').json()
            professor_name = result2[0].get('FirstName') + " " + result2[0].get('LastName')
            
            # this html and css was generated by ChatGPT
            st.markdown(f"""
                <div style="border: 1px solid #ddd; padding: 15px; margin-bottom: 10px; border-radius: 5px; box-shadow: 2px 2px 5px rgba(0,0,0,0.1);">
                    <h3 style="margin-bottom: 5px; color: #4CAF50;">{position_name}</h3>
                    <p style="margin-bottom: 5px; color: #555;"><strong>Research Area:</strong> {research_area}</p>
                    <p style="margin-bottom: 5px; color: #555;"><strong>Department:</strong> {department_name}</p>
                    <p style="margin-bottom: 5px; color: #555;"><strong>Professor:</strong> {professor_name}</p>
                    <p style="margin-bottom: 10px; color: #777;">{description}</p>
                    <p style="margin-bottom: 5px; color: #777;"><strong>Created At:</strong> {created_at}</p>
                </div>
            """, unsafe_allow_html=True)
  else:
      st.warning("No research opportunities")


if st.button("Back"):
    st.switch_page('pages/00_Undergraduate_Home.py')