import logging
logger = logging.getLogger(__name__)

import streamlit as st
import requests
from modules.nav import SideBarLinks

st.set_page_config(layout = 'wide')

# Show appropriate sidebar links for the role of the currently logged in user
SideBarLinks()

# set the header of the page
st.header('Students')

results = requests.get('http://api:4000/s/students').json()

if results:
    for student in results:
        student_id = student.get('StudentId', 'No Id')
        student_firstname = student.get('FirstName', 'No First Name')
        student_lastname = student.get('LastName', 'No Last Name')
        student_email = student.get('Email', 'No Email')
        student_skillid = student.get('SkillId', 'No Skill ID')
        student_departmentid = student.get('DepartmentId', 'No Department ID')
        student_interest = student.get('ResearchInterest', 'No Reserach Interest')
        student_year = student.get('Year', 'No Year')
        student_major = student.get('Major', 'No Major')
        student_type = student.get('StudentType', 'No Student Type')
        
        response1 = requests.get(f'http://api:4000/sk/skills/s{student_skillid}').json()
        skill_name = response1[0].get('Name', 'No Name')
        
        response2 = requests.get(f'http://api:4000/d/departments/d{student_departmentid}').json()
        department_name = response2[0].get('Name', 'No Name')
        
        # this html and css was generated by ChatGPT
        st.markdown(f"""
            <div style="border: 1px solid #2C3E50; padding: 18px; margin-bottom: 15px; border-radius: 10px; box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.15); background-color: #2C3E50;">
                <h3 style="margin-bottom: 10px; color: #76C7C0;">{student_firstname + ' ' + student_lastname}</h3>
                <p style="margin-bottom: 6px; color: #ECF0F1;"><strong>Email:</strong> {student_email}</p>
                <p style="margin-bottom: 6px; color: #ECF0F1;"><strong>Skill:</strong> {skill_name}</p>
                <p style="margin-bottom: 6px; color: #ECF0F1;"><strong>Department:</strong> {department_name}</p>
                <p style="margin-bottom: 6px; color: #ECF0F1;"><strong>Interest:</strong> {student_interest}</p>
                <p style="margin-bottom: 6px; color: #ECF0F1;"><strong>Year:</strong> {student_year}</p>
                <p style="margin-bottom: 6px; color: #ECF0F1;"><strong>Major:</strong> {student_major}</p>
                <p style="margin-bottom: 6px; color: #ECF0F1;"><strong>Type:</strong> {student_type}</p>
                <a href="mailto:{student_email}" style="display: inline-block; padding: 8px 16px; margin-top: 10px; background-color: #76C7C0; color: #2C3E50; text-decoration: none; border-radius: 5px; font-weight: bold;">Contact {student_firstname}</a>
            </div>
        """, unsafe_allow_html=True)
else:
    st.warning("No Students")

if st.button('Back'):
    st.switch_page('pages/10_Graduate_Home.py')