import logging
import pandas as pd
import streamlit as st
import requests
from modules.nav import SideBarLinks
import numpy as np

# Call the SideBarLinks from the nav module in the modules directory
SideBarLinks()

# Set the header of the page
st.header('Student Engagement Report')

# Add a button to fetch and display the report
if st.button('Generate Engagement Report',
             type="primary"):
    
    response = requests.get('http://api:4000/s/students').json()
    total_students = len(response)
    
    response2 = requests.get('http://api:4000/pr/professors').json()
    total_professors = len(response2)
    
    response3 = requests.get('http://api:4000/o/opportunities').json()
    total_opportunities = len(response3)
    
    response4 = requests.get('http://api:4000/a/applications').json()
    total_applications = len(response4)
    
    # This HTML and CSS was generated by ChatGPT
    st.markdown(f"""
            <div style="border: 1px solid #3D4A59; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); background-color: #3D4A59;">
                <h3 style="margin-bottom: 10px; color: #90AEAD;">Total Students</h3>
                <p style="margin-bottom: 8px; color: #D1D7DC;">Count: <strong>{total_students}</strong></p>
            </div>

            <div style="border: 1px solid #3D4A59; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); background-color: #3D4A59;">
                <h3 style="margin-bottom: 10px; color: #90AEAD;">Total Professors</h3>
                <p style="margin-bottom: 8px; color: #D1D7DC;">Count: <strong>{total_professors}</strong></p>
            </div>

            <div style="border: 1px solid #3D4A59; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); background-color: #3D4A59;">
                <h3 style="margin-bottom: 10px; color: #90AEAD;">Total Opportunities</h3>
                <p style="margin-bottom: 8px; color: #D1D7DC;">Count: <strong>{total_opportunities}</strong></p>
            </div>

            <div style="border: 1px solid #3D4A59; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); background-color: #3D4A59;">
                <h3 style="margin-bottom: 10px; color: #90AEAD;">Total Applications</h3>
                <p style="margin-bottom: 8px; color: #D1D7DC;">Count: <strong>{total_applications}</strong></p>
            </div>
                """, unsafe_allow_html=True)
    
# Back button
if st.button("Back"):
    st.switch_page('pages/30_Admin_Home.py')